name: GitHub Pages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install packages
      uses: bahmutov/npm-install@v1

    - name: Build page
      run: yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        publish_dir: ./build
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
